const categorias= [
  {
    "titulo": "Detection - Measurement",
    "subcategorias": [
      {
        "subtitulo": "Flow, Pressure and Level Measurement",
        "items": [
          "Flow sensors - A001",
          "Flow transmitters - A002",
          "Flow switches - A003",
          "Flow meters - A004",
          "Flow meter accessories - A006",
          "Pressure sensors - A008",
          "Pressure transducers - A009",
          "Pressure transmitters - A010",
          "Pressure switches - A011",
          "Vacuum gauges - A012",
          "Pressure gauges - A013",
          "Diaphragm seals - A014",
          "Pressure calibrators - A016",
          "Leak detectors - A017",
          "Tightness testers - A018",
          "Calibration pumps - A019",
          "Level switches - A021",
          "Level sensors - A022",
          "Level transmitters - A023",
          "Level indicators - A024",
          "Other flow, pressure and level measurement equipment - A026"
        ]
      },
      {
        "subtitulo": "Temperature and Humidity Measurement",
        "items": [
          "Temperature sensors - A101",
          "Thermistors - A102",
          "Thermocouples - A103",
          "Thermowells - A104",
          "Connection heads - A105",
          "Temperature transmitters - A106",
          "Temperature sensor accessories - A107",
          "Thermostats - A108",
          "Thermometers - A110",
          "Pyrometers - A111",
          "Temperature indicators - A112",
          "Thermal imaging cameras - A113",
          "Humidity sensors - A115",
          "Temperature and humidity sensors - A116",
          "Hygrometers - A117",
          "Anemometers - A118",
          "Rain gauges - A119",
          "Weather stations - A120",
          "Temperature calibrators - A122",
          "Multifunction calibrators, other calibrators - A123",
          "Other temperature and humidity measurement equipment - A125"
        ]
      },
      {
        "subtitulo": "Position, Speed and Acceleration Measurement",
        "items": [
          "Rotary encoders - A201",
          "Linear encoders - A202",
          "Resolvers - A204",
          "Position sensors - A206",
          "Position indicators - A207",
          "Displacement sensors - A208",
          "Distance sensors - A209",
          "Tachometers - A211",
          "Speed sensors - A212",
          "Accelerometers - A213",
          "Inclinometers - A214",
          "Proximity sensors - A216",
          "Position switches - A218",
          "Light curtains - A219",
          "Photoelectric sensors - A221",
          "Optical forks - A222",
          "Color sensors - A223",
          "Contrast detectors - A224",
          "Luminescence detectors - A225",
          "Other position, speed and acceleration measurement systems - A227",
          "Other sensors - A228"
        ]
      },
      {
        "subtitulo": "Flow, Pressure and Level Measurement",
        "items": [
          "Load cells - A301",
          "Dynamometers - A302",
          "Torque sensors - A303",
          "Torque meters - A304",
          "Strain gauges - A305",
          "Strain sensors - A306",
          "Scales - A308",
          "Crane scales - A309",
          "Weighbridges - A310",
          "Axle scales - A311",
          "Pallet scales - A312",
          "Onboard weighing systems - A313",
          "Weigh modules - A314",
          "Weight indicators - A315",
          "Weighing terminals - A316",
          "Load indicators - A317",
          "Other load measuring devices - A319"
        ]
      },
      {
        "subtitulo": "Optical and Acoustic Measurement",
        "items": [
          "Sound level meters - A401",
          "Noise dosimeters - A402",
          "Microphones - A403",
          "Sound level calibrators - A404",
          "Accelerometers - A406",
          "Vibration sensors - A407",
          "Vibration meters - A408",
          "Noise analyzers - A409",
          "Portable vibration analyzers / data collectors - A410",
          "Spectrophotometers - A411",
          "Spectroradiometers - A412",
          "Colorimeters - A413",
          "Glossmeters - A414",
          "Light meters - A416",
          "Luminance meters - A417",
          "Photometers - A418",
          "Refractometers - A420",
          "Polarimeters - A421",
          "Laser beam profilers - A423",
          "Ellipsometers - A424",
          "Interferometers - A425",
          "Pyranometers - A426",
          "Stroboscopes - A427",
          "Image sensors - A428",
          "Other acoustic and optical measurement equipment - A429",
          "Miscellaneous sensors - A431"
        ]
      },
      {
        "subtitulo": "Electrical Measurement",
        "items": [
          "Multimeters - A501",
          "Voltmeters - A502",
          "Ammeters - A503",
          "Power meters - A504",
          "Power analyzers - A505",
          "Electric energy meters - A506",
          "Ohmmeters - A507",
          "Capacitance meters - A508",
          "LCR meters - A509",
          "Hipot testers - A510",
          "Current sensors - A511",
          "AC voltage detector - A512",
          "Gaussmeters - A513",
          "Electrical network analyzers - A514",
          "Signal generators - A516",
          "Function generators - A517",
          "Arbitrary waveform generators - A518",
          "Pulse generators - A519",
          "Oscilloscopes - A521",
          "Spectrum analyzers - A522",
          "Frequency counters - A523",
          "Electrical safety testers - A525",
          "Impedance testers - A526",
          "Voltage testers - A527",
          "Continuity testers - A528",
          "Resistance testers - A529",
          "Insulation resistance testers - A530",
          "Insulation testers - A531",
          "Electronic loads - A533",
          "Other electrical measurement equipment - A535",
          "Miscellaneous sensors - A536"
        ]
      }
    ]
  },
  {
    "titulo": "METROLOGY - LABORATORY",
    "subcategorias": [
      {
        "subtitulo": "Analytical Instrumentation",
        "items": [
          "Photometers - B001",
          "Colorimeters - B002",
          "Spectrophotometers - B003",
          "Spectrometers - B005",
          "Spectrofluorometers - B006",
          "Diffractometers - B007",
          "Particle size analyzers - B008",
          "Chromatographs - B010",
          "Chromatograph accessories - B011",
          "Samplers - B013",
          "Elemental analyzers - B014",
          "Other materials characterization instruments - B015",
          "Other laboratory analyzers - B016",
          "Calorimeters - B018",
          "Thermal conductivity analyzers - B019",
          "Liquids analyzers - B021",
          "Probes - B023",
          "PH electrochemical electrodes - B024",
          "ORP electrochemical electrodes - B025",
          "Conductivity electrochemical electrodes - B026",
          "Conductivity meters - B027",
          "PH meters - B028",
          "Turbidity meters - B029",
          "Refractometers - B030",
          "Polarimeters - B031",
          "Titrators - B032",
          "Gas sensors - B034",
          "Gas transmitters - B035",
          "Gas detection control units - B036",
          "Gas detectors - B037",
          "Gas analyzers - B039",
          "Combustion analyzers - B040",
          "Particle counters - B041",
          "Calibrators for gas detectors and analyzers - B043",
          "Other analytical equipment - B044"
        ]
      },
      {
        "subtitulo": "Metrology and Test Equipment",
        "items": [
          "Measuring systems - B101",
          "Measuring machines - B102",
          "Coordinate measuring machines - B103",
          "Profilometers - B104",
          "Measuring instruments - B105",
          "3D measuring arms - B106",
          "Profile projectors - B107",
          "3D scanners - B108",
          "Profile scanners - B109",
          "Crankshaft Distortion Dial/Strain Gage - B110",
          "Calipers - B111",
          "Depth gauges - B112",
          "Height gauges - B113",
          "Micrometers - B114",
          "Thickness gauges - B115",
          "Comparators - B116",
          "Precision levels - B117",
          "Alignment systems - B118",
          "Touch probes - B120",
          "Flaw detectors - B122",
          "Coating thickness gauges - B123",
          "X-ray inspection machines - B124",
          "High Voltage Testing Equipment (VLF Testers – AC Hipot – DC Hipot– Partial Discharge Systems) - B125",
          "Testing devices, Earth resistance tester, earth ground tester - B126",
          "Test kits - B127",
          "Testing machines - B128",
          "Extensometers - B129",
          "Hardness testers - B130",
          "Density meters - B131",
          "Viscometers - B132",
          "Rheometers - B133",
          "Tensiometers - B134",
          "Moisture meters - B135",
          "Test chambers - B137",
          "Climate chambers - B138",
          "Test benches - B139",
          "Balancing machines - B140",
          "Load banks - B142",
          "Other measuring devices - B144"
        ]
      },
      {
        "subtitulo": "Inspection and Monitoring",
        "items": [
          "Inspection machines - B201",
          "Inspection systems - B202",
          "Inspection robots - B203",
          "Industrial endoscopes - B205",
          "Borescopes - B206",
          "UAVs - B208",
          "Drone equipment - B209",
          "Cameras - B211",
          "Thermal imaging cameras - B212",
          "Vision sensors - B213",
          "Vision systems - B214",
          "Lenses - B215",
          "Machine vision lights - B216",
          "Monitoring systems - B218",
          "Tracking systems - B219",
          "Data acquisition systems - B221",
          "Signal conditioners - B222",
          "Signal converters - B223",
          "Data-loggers - B224",
          "Recorders - B225",
          "Transient recorders - B226",
          "Other inspection and monitoring equipment - B227",
          "Leak detection inspection device - B228"
        ]
      },
      {
        "subtitulo": "Laboratory Equipment",
        "items": [
          "Laboratory glassware - B301",
          "Pipettes - B302",
          "Capsule filters - B303",
          "Laboratory material - B304",
          "Laboratory autoclaves - B306",
          "Microscopes - B308",
          "Laboratory scales - B309",
          "Laboratory mixers - B310",
          "Laboratory stirrers - B311",
          "Laboratory centrifuges - B312",
          "Laboratory evaporators - B313",
          "Freeze dryers - B314",
          "Sample preparation - B315",
          "Laboratory automation equipment - B316",
          "Dry block heaters - B318",
          "Heating mantles - B319",
          "Water baths - B320",
          "Thermostatic baths - B321",
          "Cryostats - B322",
          "Laboratory reactors - B323",
          "Laboratory furnaces - B325",
          "Laboratory ovens - B326",
          "Incubators - B327",
          "Refrigerators - B329",
          "Laboratory freezers - B330",
          "Extractor hoods - B332",
          "Fume hoods - B333",
          "Glove boxes - B334",
          "Laboratory water purification units - B336",
          "Other laboratory equipment - B338"
        ]
      },
      {
        "subtitulo": "Optical Components",
        "items": [
          "Optical lens elements - B401",
          "Optical filters - B402",
          "Collimators - B403",
          "Prisms - B404",
          "Lasers - B406",
          "Pulsed lasers - B407",
          "Continuous lasers - B408",
          "Laser pointers - B409",
          "Laser diodes - B410",
          "Photodiodes - B411",
          "Laser diode arrays - B412",
          "Laser heads - B413",
          "Lasers systems - B414",
          "Light sources - B416",
          "X-ray generators - B417",
          "LEDs - B418",
          "Fiber optic transceivers - B420",
          "Multiplexers - B421",
          "Lenses - B423",
          "Lens holders - B425",
          "Mirror holders - B426",
          "Filter/mirror/lens holders - B427",
          "Optical adapters - B428",
          "Other optical components - B430"
        ]
      }
    ]
  },
  {
    "titulo": "ROBOTICS - AUTOMATION - INDUSTRIAL IT",
    "subcategorias": [
      {
        "subtitulo": "Automation",
        "items": [
          "PLCs - C001",
          "Safety relays - C002",
          "Temperature control - C004",
          "Temperature regulators - C005",
          "Valve controllers - C006",
          "Pump controllers - C007",
          "Generator set controllers - C008",
          "Remote terminal units - C009",
          "Other controllers and regulators - C010",
          "Terminal - C012",
          "Indicators - C013",
          "Displays - C014",
          "Counters - C015",
          "Other counters - C016",
          "Converters - C018",
          "Gateways - C019",
          "I/O modules - C020",
          "Input modules - C021",
          "Output module - C022",
          "I/O cards - C023",
          "Modems - C024",
          "Communication routers - C025",
          "Network switches - C027",
          "Other network communication equipment - C029",
          "Transceivers - C031",
          "Radio transmitters - C032",
          "Access points - C033",
          "Antennas - C034",
          "Other wireless network communication equipment - C035",
          "Remote controls - C037",
          "Pedals - C038",
          "Joysticks - C039",
          "Indicator lights - C040",
          "RFID readers - C042",
          "RFID reader-writers - C043",
          "Barcode readers - C044",
          "Other automation equipment - C045",
          "Phase sequence indicator - C046"
        ]
      },
      {
        "subtitulo": "Industrial Robotics",
        "items": [
          "Cobots - C101",
          "Articulated robot - C103",
          "Cartesian robot - C104",
          "SCARA robot - C105",
          "Parallel robot - C106",
          "Hexapods - C107",
          "Robotic cells - C108",
          "Industrial robots - C110",
          "Welding robot - C111",
          "Painting robot - C112",
          "Palletizing robot - C113",
          "Loading robot - C114",
          "Pick-and-place robots - C115",
          "Grippers - C117",
          "Robotic tool changers - C118",
          "Robot controllers - C119",
          "Other robotic components - C120"
        ]
      },
      {
        "subtitulo": "Service Robotics",
        "items": [
          "Telepresence robots - C201",
          "Reception robots - C202",
          "Surveillance robots - C203",
          "UAVs - C204",
          "Drone equipment - C205",
          "Inspection robots - C206",
          "AGVs - C207",
          "Cleaning robots - C208",
          "Demolition robots - C209",
          "Delivery robots - C210",
          "Other service robots - C211"
        ]
      },
      {
        "subtitulo": "Industrial Computing",
        "items": [
          "PCs - C301",
          "Panel PCs - C302",
          "Servers - C303",
          "Laptop computers - C305",
          "Tablets - C306",
          "Industrial smartphones - C307",
          "Vehicle-mount computers - C308",
          "Handheld computers - C309",
          "Edge Computing Devices - C310",
          "Monitors - C311",
          "Video projectors - C312",
          "Video walls - C313",
          "Keyboards - C315",
          "Keypads - C316",
          "Mice - C317",
          "Trackballs - C318",
          "Touch screens - C319",
          "Industrial Wearable Computing (MR/AR) - C320",
          "Memory modules - C321",
          "Hard disk drives - C322",
          "Solid-state drives - C323",
          "Device servers - C324",
          "Time servers - C325",
          "Modems - C327",
          "Communication routers - C328",
          "Network switches - C329",
          "Network security platforms - C331",
          "Other network communication equipment - C333",
          "Data cabinets - C334",
          "Chassis - C335",
          "Motherboards - C336",
          "CPU boards - C337",
          "Graphics cards - C338",
          "Video capture cards - C339",
          "Memory cards - C340",
          "Network cards - C341",
          "Controller cards - C342",
          "Acquisition cards - C344",
          "Backplanes - C345",
          "Single-board computers - C346",
          "Computer-on-modules - C347",
          "Other computer equipment - C349"
        ]
      },
      {
        "subtitulo": "Industrial Software",
        "items": [
          "Software - C401",
          "CAD software - C403",
          "CAD/CAM software - C404",
          "CAM software - C405",
          "Visualization software - C406",
          "Simulation software - C408",
          "Modeling software - C409",
          "Analysis software - C410",
          "Engineering software - C411",
          "Measurement software - C412",
          "Monitoring software - C413",
          "Automation software - C414",
          "SCADA software - C415",
          "OPC software - C416",
          "Programming software - C417",
          "Management software - C419",
          "Other software - C421"
        ]
      }
    ]
  },
  {
    "titulo": "Electricity - Electronics",
    "subcategorias": [
      {
        "subtitulo": "Energy: Production and Distribution",
        "items": [
          "Power plants, Cogeneration plants - D001",
          "Wind turbines - D002",
          "Other energy production systems - D003",
          "Steam turbine generator set - D004",
          "Photovoltaic modules - D005",
          "Solar cells - D006",
          "Solar trackers - D007",
          "PV mounting systems - D008",
          "Single-phase generator sets - D010",
          "Three-phase generator sets - D011",
          "Diesel generator sets - D012",
          "Gasoline engine generator sets - D013",
          "Gas generator sets - D014",
          "Turbines - D016",
          "Alternators - D017",
          "PTO alternators - D018",
          "Fuel cells - D019",
          "Generators - D020",
          "Lighting towers - D021",
          "Power transformers - D022",
          "Current transformers - D023",
          "Instrument transformers - D024",
          "Isolation transformers - D025",
          "Electrical power supply transformers - D026",
          "Distribution transformers - D027",
          "Pulse transformers - D028",
          "Three-phase transformers - D029",
          "Other transformers and accessories - D030",
          "Substations - D032",
          "Switchgear - D033",
          "Circuit breakers - D034",
          "Capacitor banks - D035",
          "Capacitors - D036",
          "Resistors - D037",
          "Inductors - D038",
          "Fuses - D039"
        ]
      },
      {
        "subtitulo": "Power Supplies",
        "items": [
          "AC/DC power supplies - D101",
          "AC/AC power supplies - D102",
          "DC/DC power supplies - D103",
          "Voltage transducers - D104",
          "I/O power supply modules - D105",
          "DC/DC converters - D107",
          "Current converters - D108",
          "DC/AC inverters - D109",
          "Current sources - D111",
          "Compensators - D112",
          "Power regulators - D113",
          "Voltage stabilizers - D114",
          "Power supply controllers - D115",
          "Electronic ballasts - D116",
          "UPS - D118",
          "Power strips - D119",
          "Batteries - D120",
          "Energy Storage Systems (ESS/BESS) - D121",
          "Battery isolators - D122",
          "Battery chargers - D123",
          "Jump starters - D124",
          "Other electric power supplies and equipment - D126"
        ]
      },
      {
        "subtitulo": "Switches and Relays",
        "items": [
          "Switches - D201",
          "Rocker switches - D202",
          "Rotary switches - D203",
          "Lever switches - D204",
          "Touch switches - D205",
          "Slide switches - D206",
          "Mushroom switches - D207",
          "Pull cord switches - D208",
          "Piano type switches - D209",
          "Reed switches - D211",
          "Pedals - D212",
          "Joysticks - D213",
          "Disconnect switches - D215",
          "Push-button switches - D216",
          "Load-break switches - D217",
          "Switchgear - D218",
          "Transfer switches - D219",
          "Contactors - D220",
          "Other switches and accessories - D221",
          "Switching relays - D223",
          "Remote switches - D224",
          "Protection relays - D225",
          "Relay modules - D226",
          "Timers - D228",
          "Twilight switches - D229",
          "Time switches - D230",
          "Electrical safety barriers - D232",
          "Relay sockets - D233",
          "Circuit breakers - D234",
          "Lightning rods - D236",
          "Spark gaps - D237",
          "Surge arresters - D238",
          "Type 1 surge arresters - D239",
          "Type 2 surge arresters - D240",
          "Type 3 surge arresters - D241",
          "Gas discharge tubes - D243",
          "Fuse holders - D244",
          "Fuses - D245",
          "Isolators - D246",
          "Other relays and accessories - D248"
        ]
      },
      {
        "subtitulo": "Cables, Connectors, Enclosures",
        "items": [
          "Power cables - D301",
          "Electrical data cables - D302",
          "RF electrical cables - D303",
          "Optical cables - D304",
          "Audio/video electrical cables - D305",
          "Hybrid electrical cables - D306",
          "Power cords - D307",
          "Extension cords - D308",
          "Cable harnesses - D309",
          "Busbars - D310",
          "Conductor rails - D311",
          "Electrical wire - D312",
          "Ground wires - D313",
          "Drag chains - D315",
          "Floor ducts - D316",
          "Cable trays - D317",
          "Cable ladders - D318",
          "Trunking - D319",
          "Sleeves - D320",
          "Cable glands - D321",
          "Cable entry systems - D322",
          "Cable grommets - D323",
          "Feedthroughs - D324",
          "Cable reels - D325",
          "Decoilers - D326",
          "Coilers - D327",
          "Isolators - D328",
          "Transformer bushings - D329",
          "Insulation - D330",
          "Cable accessories (insulation, connectors, etc.) - D331",
          "Data connectors - D333",
          "RF connectors - D334",
          "Electrical power supply connectors - D335",
          "Board connectors - D336",
          "Audio/video connectors - D337",
          "Hybrid connectors - D338",
          "Other connectors and accessories - D339",
          "Plugs and sockets - D341",
          "Power entry modules - D342",
          "Electrical terminals - D343",
          "Terminal blocks - D344",
          "Conductor terminals - D345",
          "Connection systems - D346",
          "Slip rings - D347",
          "Electrical enclosures - D349",
          "Distribution panels - D350",
          "Power pedestals - D351",
          "Junction boxes - D352",
          "Connector housing - D353",
          "Consoles - D354",
          "Support arm systems - D355",
          "Racks - D356",
          "Electric cabinets - D357",
          "Enclosures - D358",
          "Other cabinets and enclosures - D359",
          "EMI shielding - D361",
          "Indicator lights - D362"
        ]
      },
      {
        "subtitulo": "Electronic Components",
        "items": [
          "Resistors - D401",
          "Capacitors - D402",
          "Inductors - D403",
          "Transformers - D404",
          "Potentiometers - D405",
          "Buzzers - D406",
          "Microphones - D407",
          "Loudspeakers - D408",
          "Headsets - D409",
          "Sounders - D410",
          "EMI shielding - D411",
          "Oscillators - D413",
          "Low-pass electronic filters - D414",
          "High-pass electronic filters - D415",
          "Band-pass electronic filters - D416",
          "Resonators - D417",
          "Attenuators - D418",
          "Phase shifters - D419",
          "Delay lines - D420",
          "Isolators - D421",
          "Clock generators - D422",
          "Diodes - D424",
          "Transistors - D425",
          "Gate drivers - D426",
          "Switches - D428",
          "Switching relays - D429",
          "Memory modules - D431",
          "Memory chips - D432",
          "Clock modules - D433",
          "Processors and Controllers (MPU, MCU, DSP) - D434",
          "Transceivers - D436",
          "Electronic couplers - D437",
          "Image sensors - D438",
          "IC converters - D439",
          "Peripheral line drivers, Bus controllers, Network controllers - D441",
          "Amplifiers - D442",
          "Power management - D443",
          "Graphics display controllers - D445",
          "Modems - D446",
          "Converter cards - D448",
          "Converters - D449",
          "Ferrite cores - D451",
          "Electronic fans - D452",
          "Thermal conductor film - D453",
          "Heat sinks - D454",
          "Printed circuit boards - D455",
          "Test sockets - D456",
          "Resins - D457",
          "Varnishes - D458",
          "Developer's kits - D459",
          "Other electronic components - D460"
        ]
      }
    ]
  },
  {
    "titulo": "Power Transmission - Mechanical components",
    "subcategorias": [
      {
        "subtitulo": "Bearings and Linear Guides",
        "items": [
          "Ball bearings - E101",
          "Roller bearings - E102",
          "Needle bearings - E103",
          "Needle cages - E104",
          "Slewing rings - E105",
          "Thrust ball bearings - E106",
          "Roller thrust bearings - E107",
          "Bearing pullers - E109",
          "Bearing units - E111",
          "Plain bearings - E112",
          "Guide bushings - E113",
          "Ball joints, Wheel type rollers - E114",
          "One-way clutches - E115",
          "Bearing and bearing unit components and accessories - E116",
          "Linear guides - E118",
          "Linear bearings - E119",
          "Shafts - E120",
          "Rails - E121",
          "Other guide accessories and components - E123"
        ]
      },
      {
        "subtitulo": "Mechanical Transmission",
        "items": [
          "Trapezoidal belts - E201",
          "Flat belts - E202",
          "Round belts - E203",
          "Ribbed belts - E204",
          "Synchronous belts - E205",
          "Belt drives systems - E206",
          "Pulleys - E207",
          "Chains - E208",
          "Chain guides - E209",
          "Sprocket wheels - E210",
          "Tensioners - E211",
          "Other drives and accessories - E212",
          "Couplings - E214",
          "Rigid couplings - E215",
          "Flexible couplings - E216",
          "Torsionnaly-rigid flexible couplings - E217",
          "Cylinder rod couplings - E218",
          "Flange couplings - E219",
          "Sleeve couplings - E220",
          "Hydrodynamic couplings - E221",
          "Other couplings and accessories - E222",
          "Torque limiters - E224",
          "Shafts - E225",
          "Universal joints - E226",
          "One-way clutches - E227",
          "Brakes - E229",
          "Electromagnetic brakes - E230",
          "Hydraulic brakes - E231",
          "Pneumatic brakes - E232",
          "Brake calipers - E233",
          "Clamping - E234",
          "Other brakes and accessories - E235",
          "Clutches - E237",
          "Electromagnetic clutches - E238",
          "Pneumatic clutches - E239",
          "Hydraulic clutches - E240",
          "Spring clutches - E241",
          "Other clutches and accessories - E242",
          "Planetary gear reducers - E244",
          "Gear train gear reducers - E245",
          "Bevel gear reducers - E246",
          "Worm gear reducers - E247",
          "Strain wave gear reducers - E248",
          "Magnetic gear reducers - E249",
          "Special gear reducers - E250",
          "Angle gearboxes - E251",
          "Ball screws - E253",
          "Roller screws - E254",
          "Lead screws - E255",
          "Gears - E256",
          "Racks and pinions - E257"
        ]
      },
      {
        "subtitulo": "Actuators and Positioning Systems",
        "items": [
          "Single-acting cylinders - E301",
          "Double-acting cylinders - E302",
          "Pneumatic cylinders - E303",
          "Hydraulic cylinders - E304",
          "Rotary cylinders - E305",
          "Other hydraulic cylinders - E306",
          "Actuators - E308",
          "Electric cylinders - E309",
          "Screw jacks - E310",
          "Linear modules - E311",
          "Linear axis - E312",
          "Piezoelectric motors - E313",
          "Solenoids - E315",
          "Transaxles - E316",
          "Lifting columns - E317",
          "Slides - E318",
          "Other actuators and positioning accessories - E319",
          "Positioning stages - E321",
          "Positioners - E322",
          "Rotary tables - E323",
          "Lift tables - E324",
          "Positioning systems - E325",
          "Other positioning stages - E326",
          "Indexers - E328",
          "Feeders - E329"
        ]
      }
    ]
  },
  {
    "titulo": "Hydraulics - Pneumatics",
    "subcategorias": [
      {
        "subtitulo": "Pumps",
        "items": [
          "Water pumps - F001",
          "Chemical pumps - F002",
          "Food product pumps - F003",
          "Slurry pumps - F004",
          "Grease pumps - F005",
          "Oil pumps - F006",
          "Air pumps - F007",
          "Fuel pumps - F008",
          "LPG / Cryogenic pumps - F009",
          "Centrifugal pumps - F010",
          "Diaphragm pumps - F011",
          "Piston pumps - F012",
          "Peristaltic pumps - F013",
          "Gear pumps - F014",
          "Screw pumps (muy usadas en Oil & Gas) - F015",
          "Vacuum generators - F016",
          "Vacuum pumps - F017",
          "Venturi ejectors - F018",
          "Metering pumps - F020",
          "Hydraulic pumps - F021",
          "Progressive cavity pumps - F022",
          "Pumping units - F023",
          "Pumping stations - F024",
          "Pump accessories - F026",
          "Pump control systems - F027",
          "Pump motors & drivers - F028",
          "Pump skid packages - F029",
          "Pump Seal Kits - F030",
          "Pump Hydraulic Components - F031",
          "Pump Mechanical Components - F032"
        ]
      },
      {
        "subtitulo": "Compressors",
        "items": [
          "Stationary compressors - F101",
          "Mobile compressors - F102",
          "Centrifugal compressors - F104",
          "Screw compressors - F105",
          "Rotary vane compressors - F106",
          "Piston compressors - F107",
          "Air compressors - F109",
          "Gas compressors - F110",
          "Engine-driven compressors - F111",
          "Pressure boosters - F113",
          "Compressor stations - F114",
          "Blowers - F116",
          "Turbo-blowers - F117",
          "Blower units - F118",
          "Other blowers - F119",
          "Refrigeration compressors - F121",
          "Hydraulic power units - F122",
          "Turbo-compressors - F124"
        ]
      },
      {
        "subtitulo": "Hydraulic and Pneumatic Actuators",
        "items": [
          "Hydraulic actuators - F201",
          "Pneumatic actuators - F202",
          "Hydraulic cylinders - F204",
          "Pneumatic cylinders - F205",
          "Rotary cylinders - F206",
          "Hydraulic motors - F208",
          "Air motors - F209",
          "Other actuators and accessories - F211"
        ]
      },
      {
        "subtitulo": "Valves",
        "items": [
          "Valves - F301",
          "Ball valves - F302",
          "Gate valves - F304",
          "Butterfly valves - F305",
          "Pinch valves - F306",
          "Diaphragm valves - F307",
          "Globe valves - F308",
          "Needle valves - F309",
          "Piston valves - F310",
          "Slide valves - F311",
          "Shut-off valves - F313",
          "Regulating valves - F314",
          "Control valves - F315",
          "Check valves - F317",
          "Release valves - F318",
          "Rupture discs - F319",
          "Manifolds - F321",
          "Directional control valves - F323",
          "Solenoid valves - F325",
          "Direct-operated solenoid valves - F326",
          "Pilot-operated solenoid valves - F327",
          "Valve actuators - F329",
          "Pressure regulators - F330",
          "Flow regulators - F331",
          "Flow dividers - F332",
          "Other accessories and components - F334"
        ]
      },
      {
        "subtitulo": "Pipes, Tubes and Fittings",
        "items": [
          "Pneumatic fittings - F401",
          "Hydraulic fittings - F402",
          "Quick couplings - F403",
          "Rotary unions - F404",
          "Banjo fittings - F405",
          "Socket fittings - F406",
          "Screw-in fittings - F407",
          "Plugs - F409",
          "Nipples - F410",
          "Flanges - F411",
          "Pipe adapters - F412",
          "Pipe couplers - F413",
          "Bushings - F414",
          "Pipe expansion joints - F415",
          "Ferrules - F416",
          "Hoses - F418",
          "Pipes - F419",
          "Hose reels - F420",
          "Pipe and hose accessories - F421",
          "Nozzles - F423",
          "Fueling nozzles - F424",
          "Air blow guns - F426",
          "Cleaning guns - F427",
          "Blower guns - F428",
          "Accumulators - F430",
          "Sight glasses - F431"
        ]
      },
      {
        "subtitulo": "Filters and Separators",
        "items": [
          "Filters - F501",
          "Air filters - F503",
          "Compressed air filters - F504",
          "Liquid filters - F505",
          "Hydraulic filters - F506",
          "Gas filters - F507",
          "Fume filters - F508",
          "Steam filters - F509",
          "Cartridge filters - F511",
          "Basket filters - F512",
          "Panel filters - F513",
          "Strainer filters - F514",
          "Filter presses - F516",
          "Filtration systems - F517",
          "Filtration units - F518",
          "Silencers - F520",
          "Other filters and accessories - F521",
          "Separators - F523",
          "Centrifugal separators - F525",
          "Magnetic separators - F526",
          "Gravity separators - F527",
          "Liquids separators - F529",
          "Gas separators - F530",
          "Solids separators - F531",
          "Gas separators - F532",
          "Drains - F534",
          "Breathers - F535",
          "Decanters - F537",
          "Settling tanks - F538",
          "Hydrocyclones - F540",
          "Filter cartridges - F542",
          "Filter housings - F543",
          "Filter diaphragms - F545",
          "Filter pads - F546",
          "Filter media - F547",
          "Filter bags - F548",
          "Other filter material and accessories - F550"
        ]
      }
    ]
  },
  {
    "titulo": "MATERIALS - TOOLS - COMPONENTS",
    "subcategorias": [
      {
        "subtitulo": "Semi-finished products",
        "items": [
          "Steel - G001",
          "Stainless steel - G002",
          "Aluminum - G003",
          "Aluminum alloys - G004",
          "Copper - G005",
          "Copper alloys - G006",
          "Other metal alloys - G007",
          "Other pure metals - G008",
          "Polyester - G010",
          "PVC - G011",
          "PTFE - G012",
          "Polystyrene - G013",
          "Polypropylene - G014",
          "Polyethylene - G015",
          "Elastomers - G016",
          "other plastics - G017",
          "Ceramics - G019",
          "Glass - G020",
          "Crystals - G021",
          "Fibers - G023",
          "Resins - G024",
          "Prepregs - G025",
          "Honeycombs - G026",
          "AlNiCo magnets - G028",
          "Ferrite magnets - G029",
          "SmCo magnets - G030",
          "NdFeB magnets - G031",
          "Varnishes - G033",
          "Paints - G034",
          "Gases - G035",
          "Other chemical products - G036",
          "Chemical Defoaming Agent - G037",
          "Other materials - G038",
          "Abrasive Grinding & Lapping Compounds - G039"
        ]
      },
      {
        "subtitulo": "Lubrication",
        "items": [
          "Lubricants - G101",
          "Oils - G102",
          "Greases - G103",
          "Pastes - G104",
          "Dry lubricants - G105",
          "Lubricators - G107",
          "Oilers - G108",
          "Lubrication units - G109",
          "Lubrication pumps - G110",
          "Other lubrication equipment - G111",
          "Metalworking fluids - G113",
          "Cutting oils - G114",
          "Release agents - G116",
          "Penetrating oils - G117"
        ]
      },
      {
        "subtitulo": "Hand Tools, Power Tools",
        "items": [
          "Electric screwdrivers - G201",
          "Air screwdrivers - G202",
          "Nutrunners - G203",
          "Impact wrenches - G204",
          "Wrenches - G205",
          "Allen wrench - G206",
          "Sockets - G207",
          "Ratchet wrenches - G208",
          "Torque wrenches - G209",
          "Screwdrivers - G210",
          "Screwdriver bits - G211",
          "Bit holders - G212",
          "Drills - G213",
          "Rotary hammers - G214",
          "Portable boring machines - G215",
          "Pliers - G217",
          "Wire strippers - G218",
          "Cable cutters - G219",
          "Bar clamps - G220",
          "Bearing pullers - G221",
          "Portable saws - G223",
          "Manual saws - G224",
          "Jigsaws - G225",
          "Sabre saws - G226",
          "Handheld circular saws - G227",
          "Handheld miter saws - G228",
          "Chainsaws - G229",
          "Portable chamfering machines - G230",
          "Portable cable cutters, Cutting pliers, Wire and cable strippers - G231",
          "Polishers - G233",
          "Handheld portable grinders - G234",
          "Handheld sanders - G235",
          "Staplers - G237",
          "Riveters - G238",
          "Nail guns - G239",
          "Crimping tools - G240",
          "Strapping tools - G241",
          "Handheld bending machines - G243",
          "Pipe cutters - G244",
          "Cable pullers - G246",
          "Brushes - G247",
          "Flashlights - G248",
          "Head lamps - G249",
          "Portable floodlights - G250",
          "Flashlights - G251",
          "Other tools - G252",
          "Sledge hammer, Brass sledge, - G254",
          "Rubber hammer - G255",
          "Construction site hammers - G256",
          "hammer , Safety hammer, Installation hammer - G257"
        ]
      },
      {
        "subtitulo": "Automotive maintenance equipment",
        "items": [
          "Car lifts - G301",
          "Shop cranes - G302",
          "Jacks - G303",
          "Jack stands - G304",
          "Tire changers - G306",
          "Wheel balancers - G307",
          "Alignment machines - G308",
          "Exhaust extraction systems - G309",
          "Impact wrenches - G310",
          "Battery chargers - G312",
          "Jump starters - G313",
          "Diagnostic tools - G314",
          "Air conditioning stations - G315",
          "Air blow guns - G317",
          "Oil lift drains - G318",
          "Tool cabinets - G319",
          "Workbenches - G320",
          "Cable reels - G321",
          "Radiant heaters - G322",
          "Parts washers - G323",
          "Paint booths - G325",
          "Air compressors - G326",
          "Other automotive maintenance equipment - G328"
        ]
      },
      {
        "subtitulo": "Auto body shop equipment",
        "items": [
          "Paint booths - G401",
          "Air compressors - G402",
          "Blast cabinets - G403",
          "Paint mixers - G404",
          "Paint guns - G405",
          "Paint spray units - G406",
          "Automotive cleaning machines - G407",
          "Paint preparation stations - G409",
          "Bodywork supports - G410",
          "Sanders - G412",
          "Auto body abrasives - G413",
          "Car repair benches - G414",
          "Dent removal kits - G415",
          "Spotters - G416",
          "Slide hammers - G417",
          "Glue guns - G418",
          "Welders - G419",
          "Manipulator arms - G420",
          "Masking tapes - G421",
          "Auto body paints - G423",
          "Auto body primers - G424",
          "Auto body varnishes - G425",
          "Auto body sealants - G426",
          "Gowns - G428",
          "Safety glasses - G429",
          "Respirators - G430",
          "Other auto body equipment - G432"
        ]
      },
      {
        "subtitulo": "Standard Mechanical Components",
        "items": [
          "Screws - G501",
          "Bolts - G502",
          "Studs - G503",
          "Nuts - G504",
          "Washers - G505",
          "Rivets - G506",
          "Inserts - G507",
          "Standoffs - G508",
          "Thread inserts - G509",
          "Blind rivet nuts - G510",
          "Pins - G511",
          "Retaining rings - G512",
          "Locking pins - G513",
          "Clevis pins - G514",
          "Shims - G515",
          "Spacers - G516",
          "Hose clamps - G517",
          "Cable tie mounts - G518",
          "Fixing clips - G519",
          "Cable ties - G520",
          "Toggle clamps - G521",
          "Quick-release pins - G522",
          "Spring plungers - G523",
          "Indexing plungers - G524",
          "Locating pins - G525",
          "Ball plungers - G526",
          "Supports - G527",
          "Other attachment devices - G528",
          "Hinges - G530",
          "Lid stays - G531",
          "Locks - G532",
          "Draw latches - G533",
          "Latches - G534",
          "Strike plates - G535",
          "Magnetic latches - G536",
          "Locking inserts - G537",
          "Cylinder locks - G538",
          "Locking devices - G539",
          "Door closers - G540",
          "Retainers - G541",
          "Slides - G543",
          "Handles - G545",
          "Clamping levers - G546",
          "Knobs - G547",
          "Levers - G548",
          "Handwheels - G549",
          "Crank handles - G550",
          "Wire ropes - G552",
          "Metal profiles, Modular structure profiles - G554",
          "Modular structure fittings - G555",
          "Plugs - G557",
          "Caps - G558",
          "Bolt and nut caps - G559",
          "Springs - G561",
          "Air springs - G562",
          "Gas springs - G563",
          "Dampers - G564",
          "Shock dampers - G565",
          "Stops - G566",
          "Bumpers - G567",
          "Thrust pads - G568",
          "Anti-vibration mounts - G569",
          "Rotary dampers - G570",
          "Dampers with speed control - G571",
          "Other dampers - G572",
          "Feet - G574",
          "Wheels - G575",
          "Casters - G576",
          "Cable glands - G578",
          "Cable protectors - G579",
          "Cable entry systems - G580",
          "Cable entry frames - G581",
          "Feedthroughs - G582",
          "Mechanical seals - G584",
          "Braided packing - G585",
          "Sealing rings - G586",
          "Sealing tapes - G587",
          "Seals - G589",
          "O-ring seals - G590",
          "Gasket sheets - G591",
          "Flat seals - G592",
          "Other seals - G593",
          "Balls - G595"
        ]
      },
      {
        "subtitulo": "Industrial Chemicals",
        "items": [
          "Sealants, Joint / Flange Sealants - G601",
          "adhesives - G602",
          "threadlockers - G603",
          "compounds - G604"
        ]
      }
    ]
  },
  {
    "titulo": "MACHINE-TOOLS",
    "subcategorias": [
      {
        "subtitulo": "Machining Centers",
        "items": [
          "Vertical machining centers - H001",
          "Horizontal machining centers - H002",
          "Horizontal CNC milling machines - H004",
          "Vertical CNC milling machines - H005",
          "CNC milling machines - H006",
          "Milling machines - H007",
          "Boring mills - H009",
          "Drilling and milling machines - H010",
          "Drilling machines - H012",
          "Drill presses - H013",
          "Boring machines - H014",
          "Tapping machines - H015",
          "CNC lathe - H017",
          "Swiss lathes - H018",
          "Conventional lathe - H019",
          "Milling-turning centers - H020",
          "Vertical lathe - H022",
          "Routers - H024",
          "Transfer machines - H025",
          "Copy routers - H026",
          "Broaching machines - H027",
          "Die sinking electrical discharge machines - H028",
          "electrical discharge machine - H029",
          "Other milling machines - H030",
          "Machining services - H031",
          "Machining - H033",
          "Turning machining - H034",
          "Bar turning machining - H035"
        ]
      },
      {
        "subtitulo": "Finishing Machines",
        "items": [
          "Grinding machines - H101",
          "Deburring machines - H102",
          "Chamfering machines - H103",
          "Finishing machines - H105",
          "Lapping machines - H106",
          "Honing machines - H107",
          "Polishing machines - H108",
          "Centrifugal finishing machines - H109",
          "Vibratory finishing machines - H110",
          "Super-finishing machines - H111",
          "Grinding polishing machines - H112",
          "Other finishing machines - H113",
          "Surface planers - H115",
          "Planers - H116",
          "Sanders - H117",
          "Grinding wheels - H119",
          "Abrasive belts - H120",
          "Grinding - H121"
        ]
      },
      {
        "subtitulo": "Cutting Tools",
        "items": [
          "Cutting inserts - H201",
          "Turning inserts - H202",
          "Grooving inserts - H203",
          "Milling cutters - H205",
          "Drill bits - H206",
          "Reamers - H207",
          "Boring bars - H208",
          "Boring tools - H209",
          "Counterbores - H210",
          "Thread milling cutters - H212",
          "Taps - H213",
          "Machine taps - H214",
          "Threading dies - H215",
          "Threading tools - H216",
          "Turning tools - H218",
          "Grooving tools - H219",
          "Knurling tools - H220",
          "Miscellaneous cutting tools - H222"
        ]
      },
      {
        "subtitulo": "Machine Tool Accessories",
        "items": [
          "Chucks - H301",
          "End mill holders - H302",
          "Collet chucks - H303",
          "Tool holder adapters - H304",
          "Angle heads - H305",
          "Collets - H306",
          "Turning chucks - H308",
          "Lathe centers - H309",
          "Steady rests - H310",
          "Spindles - H312",
          "Milling heads - H313",
          "Boring heads - H314",
          "Machining units - H315",
          "Drilling units - H316",
          "Drilling heads - H317",
          "Tapping units - H318",
          "Tool turrets - H319",
          "Tool changers - H320",
          "Chip conveyors - H321",
          "Rotary indexing tables - H323",
          "Rotary tables - H324",
          "Indexing rings - H325",
          "Tilting rotary tables - H326",
          "Magnetic chucks - H327",
          "Vacuum chucks - H328",
          "Clamping plates - H329",
          "Vises - H331",
          "Clamps - H332",
          "Zero-point clamping systems - H333",
          "Other clamping elements - H334",
          "Tool presetters - H336",
          "Terminal - H338",
          "CNC controllers - H339",
          "Machine feed - H340",
          "Bellows - H341",
          "Other machine tool equipment - H342"
        ]
      }
    ]
  },
  {
    "titulo": "PRODUCTION MACHINES",
    "subcategorias": [
      {
        "subtitulo": "Additive Manufacturing, 3D Printing",
        "items": [
          "3D printers - I001",
          "Industrial 3D printers - I003",
          "Medical 3D printers - I004",
          "Dental 3D printers - I005",
          "Rapid prototyping machines - I006",
          "Prototyping machines - I007",
          "3D printer filament - I009",
          "3D printing resins - I010",
          "3D printing powders - I011",
          "3D printing pellets - I012",
          "3D printing scanners - I014",
          "3D printing softwares - I015",
          "3D printing - I017"
        ]
      },
      {
        "subtitulo": "Cutting Machines",
        "items": [
          "Cutting machines - I101",
          "Laser cutting machines - I102",
          "Plasma cutting machines - I103",
          "Water-jet cutting machines - I104",
          "Knife cutting machines - I105",
          "Oxy-fuel cutting machines /  Flame cutting - I106",
          "Cutting heads - I107",
          "Laser cutting heads - I108",
          "Water-jet cutting heads - I109",
          "Saws - I111",
          "Band saws - I112",
          "Circular saws - I113",
          "Panel saws - I114",
          "Wire electrical discharge machines - I116",
          "Plasma cutters - I117",
          "Other cutting machines - I118",
          "Cut-off saws - I120",
          "Bridge saws - I121",
          "Sliding table saws - I122",
          "Spindle molders - I124",
          "Shears - I126",
          "Tube cutting machines - I127",
          "Bandsaw blades - I129",
          "Circular saw blades - I130",
          "Cutting discs - I131",
          "Cutting - I133",
          "Laser cutting - I134",
          "Water-jet cutting - I135",
          "Plasma cutting - I136"
        ]
      },
      {
        "subtitulo": "Forming Machines",
        "items": [
          "Industrial presses - I201",
          "Mechanical presses - I202",
          "Hydraulic presses - I203",
          "Electric presses - I204",
          "Pneumatic presses - I205",
          "Bench-top presses - I206",
          "Membrane presses - I207",
          "Manual presses - I208",
          "Forging presses - I209",
          "Compression presses - I210",
          "Press brakes - I212",
          "Swivel folding machines - I213",
          "Robotic bending cells - I214",
          "Hydraulic Wedge Mandrel - I215",
          "Bending machines - I216",
          "Plate bending machines - I217",
          "Rolling mills - I218",
          "Roll forming machines - I219",
          "Punching machines - I221",
          "Punching presses - I222",
          "Notching machines - I223",
          "Seamers - I224",
          "Crimping heads - I225",
          "Other forming equipment - I227",
          "Deep drawing - I229",
          "Hydroforming - I230",
          "Sheet bending - I231",
          "Rolling - I232",
          "Flow forming - I233"
        ]
      },
      {
        "subtitulo": "Plastics Processing",
        "items": [
          "Injection molding machines - I301",
          "Extrusion lines - I302",
          "Extruders - I304",
          "Screen changers - I305",
          "Calibration tanks - I306",
          "Cooling baths - I307",
          "Haul-offs - I308",
          "Granulators - I309",
          "Other extrusion line equipment - I310",
          "Thermoforming machines - I312",
          "Roto-molding machines - I313",
          "Blow molding machines - I314",
          "Pre-expanders - I315",
          "Molding machines - I316",
          "Other plastic and rubber transformation machines - I317",
          "Mold bases - I319",
          "Hot runner systems - I320",
          "Injection nozzles - I321",
          "Molds and tool ejectors - I322",
          "Other mold and tool elements - I323",
          "Cartridge heaters - I325",
          "Temperature regulators - I326",
          "Plastic crystallizers - I327",
          "Plastic pellet dryers - I328",
          "Plastic mills - I329",
          "Mixing heads - I331",
          "Spray units - I332",
          "Filament winding machines - I333",
          "Composites consumables - I334",
          "Other machines for composites - I335",
          "Injection molding - I337",
          "Plastic extrusion - I338",
          "Plastic machining - I339",
          "Plastic blowing - I340",
          "Thermoforming - I341",
          "Plastic injection molds - I343",
          "Blow molds - I344",
          "Injection blow molds - I345",
          "Extrusion blow molds - I346",
          "Extrusion heads - I347",
          "Other plastic processing techniques - I349"
        ]
      },
      {
        "subtitulo": "Textile machinery",
        "items": [
          "Bale openers - I401",
          "Mixers for the textile industry - I402",
          "Carding machines - I403",
          "Spinning machines - I404",
          "Winding machines - I405",
          "Texturing machines - I406",
          "Warping machines - I408",
          "Creels - I409",
          "Weaving machines - I410",
          "Weaving accessories - I411",
          "Fabric winders - I413",
          "Fabric inspection machines - I414",
          "Fabric folding machines - I415",
          "Spreading machines - I417",
          "Fabric cutters - I418",
          "Cutting tables - I419",
          "Textile slitting machines - I420",
          "Slitter-rewinders - I421",
          "Fabric cutting machines - I422",
          "Industrial sewing machines - I423",
          "Hemming lines - I424",
          "Knitting machines - I426",
          "Embroidery machines - I427",
          "Textile baling presses - I429",
          "Other textile industry machines - I430"
        ]
      },
      {
        "subtitulo": "Machines for the electronics industry",
        "items": [
          "SMT screen printers - I501",
          "SMT pick-and-place machines - I502",
          "Reflow soldering machines - I503",
          "Selective soldering machines - I504",
          "PCB inspection machines - I506",
          "PCB depaneling machines - I507",
          "PCB routers - I508",
          "PCB loaders - I510",
          "Printed circuit conveyors - I511",
          "PCB unloaders - I512",
          "PCB magazines - I513",
          "Rework stations - I515",
          "Electronic components counters - I516",
          "Die bonders - I517",
          "Wire bonders - I518",
          "Printed circuit board production machines - I519",
          "Solder baths - I520",
          "Solder paste mixers - I521",
          "PCB cleaning machines - I522",
          "Other machines for the electronics industry - I524"
        ]
      },
      {
        "subtitulo": "Other Manufacturing Equipment",
        "items": [
          "Laser sintering machines - I601",
          "Casting machines - I603",
          "Die casting machines - I604",
          "Molding machines - I605",
          "Other foundry equipment - I606",
          "Inspection machines - I608",
          "Stripping machines - I609",
          "Edge-banding machines - I611",
          "Wood saws - I612",
          "Demagnetizers - I614",
          "Magnetizers - I615",
          "Ionizers - I616",
          "Anti-static bars - I617",
          "Mills - I619",
          "Separator screens - I620",
          "Screen plates - I621",
          "Screeners - I622",
          "Sieves - I623",
          "Technical gas production equipment - I625",
          "Production lines - I627",
          "Other production machines - I628",
          "Other production equipment - I629",
          "Sand casting - I631",
          "Lost wax casting - I632",
          "Die casting - I633",
          "Shell molding - I634",
          "Forging - I636",
          "Metal extrusion - I637",
          "Lamination - I638",
          "Sintering - I640",
          "Other metalworking processes - I642"
        ]
      }
    ]
  },
  {
    "titulo": "INDUSTRIAL MACHINES AND EQUIPMENT",
    "subcategorias": [
      {
        "subtitulo": "Surface Treatment Equipment",
        "items": [
          "Sandblasting machines - J001",
          "Blast cabinets - J002",
          "Sandblasting guns - J003",
          "Shot blasting machines - J004",
          "Bench grinders - J005",
          "Sanders - J006",
          "Scalers - J007",
          "Downdraft tables - J008",
          "Grinding wheels - J010",
          "Abrasive discs - J011",
          "Abrasive stones - J012",
          "Abrasive belts - J013",
          "Flap wheels - J014",
          "Abrasive rolls - J015",
          "Abrasive cloths - J016",
          "Polishing pads - J017",
          "Blasting media - J018",
          "Brushes - J019",
          "Knotted wheel brushes - J020",
          "Other surface treatment equipment - J021",
          "Cleaning machines - J023",
          "Ultrasonic cleaners - J024",
          "Ultrasonic cleaning generators - J025",
          "Ultrasonic transducers - J026",
          "Cleaning nozzles - J027",
          "Other cleaning machines - J028",
          "Corona effect surface treatment machines - J030",
          "Plasma surface treatment machines - J031",
          "Ionizing air guns - J032",
          "Coating guns - J034",
          "PVD deposition machines - J035",
          "CVD deposition machines - J036",
          "Galvanizing baths, phosphating, blueing - J038",
          "Galvanic processes filtration systems - J039",
          "Other electrolytic deposition equipment - J040",
          "Powder coating lines - J042",
          "Paint booths - J043",
          "Powder coating booths - J044",
          "Powder coating machines - J045",
          "Paint striping machines - J046",
          "Coating systems - J047",
          "Spray units, Airless Sprayer - J048",
          "Painting robot - J049",
          "Other painting equipment - J050",
          "Powder coating systems - J052",
          "Electrostatic guns - J053",
          "Suction paint spray guns - J055",
          "Gravity-feed paint spray guns - J056",
          "Automatic guns - J057",
          "Other paint sprayers - J058"
        ]
      },
      {
        "subtitulo": "Surface Treatment",
        "items": [
          "Anodizing - J101",
          "Sulfuric anodizing - J102",
          "Hard anodizing - J103",
          "Chromic anodizing - J104",
          "Sulfo-tartaric anodizing - J105",
          "Alodine - J107",
          "Cadmium plating - J108",
          "Phosphating - J109",
          "Etching - J110",
          "Galvanizing - J111",
          "Passivation - J112",
          "Chrome plating - J113",
          "Nickel plating - J114",
          "Sand blasting - J116",
          "Bead blasting - J117",
          "Shot blasting - J118",
          "Pickling - J119",
          "Hardening - J121",
          "Tempering - J122",
          "Annealing - J123",
          "Carburization - J124",
          "Painting - J126",
          "Powder coating - J127",
          "Other surface treatment processes - J129",
          "Polishing - J130"
        ]
      },
      {
        "subtitulo": "Welding and Assembly",
        "items": [
          "Welders - J201",
          "Welding robot - J202",
          "Welding machines - J203",
          "Brazing machines - J204",
          "Welding guns - J205",
          "Welding torch - J207",
          "Orbital welding heads - J208",
          "Welding heads - J209",
          "Welding clamps - J210",
          "Stud welding guns - J211",
          "Cutting torches - J212",
          "Wire feeders - J214",
          "Welding carriages - J215",
          "Welding consumables - J216",
          "Other welding and soldering equipment - J217",
          "Welding helmets - J219",
          "Fume extractors - J220",
          "Extraction arms - J221",
          "Soldering irons - J223",
          "Crimping machines - J225",
          "Screwing units - J226",
          "Other assembly equipment - J227",
          "Riveting machines - J229",
          "Stapling machines - J230",
          "Acrylic adhesives - J232",
          "Anaerobic adhesives - J233",
          "Cyanoacrylate adhesives - J234",
          "Epoxy adhesives - J235",
          "Polyurethane adhesives - J236",
          "Silicone adhesives - J237",
          "Adhesives - J238",
          "Threadlockers - J239",
          "Adhesive tape - J240",
          "Bonding equipment and accessories - J241",
          "Welding - J243",
          "Assembly - J245"
        ]
      },
      {
        "subtitulo": "Printing, Marking and Engraving",
        "items": [
          "Offset plates - J301",
          "CtP - J302",
          "CtP processor cleaners - J303",
          "Flexographic press - J305",
          "Offset presses - J306",
          "Pad printing machines - J307",
          "Screen printers - J308",
          "Daters - J309",
          "Numbering machines - J310",
          "Other printing machines - J311",
          "Paper cutters - J313",
          "Pile elevators - J314",
          "Paper joggers - J315",
          "Piles turners - J316",
          "Paper folding machines - J317",
          "Binding machines - J318",
          "Label printers - J320",
          "POS printers - J321",
          "Printers - J322",
          "Large format printers - J323",
          "Marking machines - J325",
          "Marking systems - J326",
          "Marking units - J327",
          "Marking devices - J328",
          "Engraving machines - J329",
          "Other marking machines - J330",
          "Machine equipment and accessories: marking, engraving, printing - J332",
          "Labels, Continuous label tape cassette - J333",
          "Inks - J334"
        ]
      },
      {
        "subtitulo": "Furnaces and Heat Treatment",
        "items": [
          "Ovens - J401",
          "Induction heaters - J403",
          "Induction heating generators - J404",
          "Shrink fit machines - J405",
          "Hardening machines - J406",
          "Autoclaves - J408",
          "Sterilizers - J409",
          "Pasteurizers - J410",
          "Freeze dryers - J412",
          "Air knives - J413",
          "Dryers - J414",
          "Compressed air dryers - J415",
          "Drying tunnels - J416",
          "Drying cabinets - J417",
          "Other thermal treatment equipment - J419",
          "Heat exchangers - J501",
          "Dry coolers - J502",
          "Coolers - J503",
          "Cooling towers - J504",
          "Condensers - J505",
          "Evaporators - J506",
          "Boilers - J508",
          "Burners - J509",
          "Burner accessories - J510",
          "Heating elements - J512",
          "Immersion heaters - J513",
          "Cartridge heaters - J514",
          "Drum heaters - J515",
          "Heating cables - J516",
          "Heated hoses - J517",
          "Coil heaters - J518",
          "Hot plates - J519",
          "Temperature control units - J520",
          "Refrigeration compressors - J522",
          "Condensing units - J523",
          "Unit coolers - J524",
          "Refrigeration system components - J525",
          "Cold rooms - J526",
          "Process freezers - J527",
          "Refrigeration units - J528",
          "Other refrigeration systems - J529",
          "Electrical cabinet air conditioners - J531",
          "Other heating and cooling equipment - J533"
        ]
      },
      {
        "subtitulo": "Mixing and Dosing",
        "items": [
          "Conical screw mixers - J601",
          "Paddle mixers - J602",
          "Ribbon mixers - J603",
          "Planetary mixers - J604",
          "Rotary drum mixers - J605",
          "Dispersers - J606",
          "Disperser mixers - J607",
          "Emulsifiers - J608",
          "High-speed mixers - J609",
          "Kneaders - J610",
          "Mixers - J611",
          "Static mixers - J612",
          "Dynamic mixers - J613",
          "Agitator impellers - J615",
          "Homogenizers - J616",
          "Batch blenders - J618",
          "Mixing heads - J619",
          "Dosing dispensers - J621",
          "Dispensing robot - J622",
          "Volumetric dosing dispensers - J623",
          "Weight dosing dispensers - J624",
          "Hopper loaders - J625",
          "Metering pumps - J626",
          "Dispensing tips - J627",
          "Dispensing cartridges - J628",
          "Dosing syringes - J629",
          "Dispensing accessories - J630"
        ]
      }
    ]
  },
  {
    "titulo": "FOOD INDUSTRY",
    "subcategorias": [
      {
        "subtitulo": "Meat Processing",
        "items": [
          "eboning machines - K001",
          "Bone band saws - K003",
          "Membrane skinning machines - K004",
          "Derinders - K005",
          "Bowl cutters - K007",
          "Meat slicing machines - K008",
          "Meat dicers - K009",
          "Frozen meat cutters - K010",
          "Meat mixers - K012",
          "Industrial mincers - K013",
          "Industrial meat mixer grinders - K014",
          "Meat emulsifiers - K015",
          "Stuffers - K017",
          "Vacuum fillers - K018",
          "Meat forming machines - K019",
          "Meat portioning machines - K020",
          "Clipping machines - K021",
          "Meat skewer machines - K022",
          "Meat tenderizers - K024",
          "Brine injector machines - K025",
          "Meat tumblers - K026",
          "Industrial fryers - K028",
          "Smoking chambers - K029",
          "Boiling pans - K030",
          "Industrial cookers - K031",
          "Ground meat production lines - K033",
          "Sausage production lines - K034",
          "Other meat processing equipment - K036"
        ]
      },
      {
        "subtitulo": "Fish Processing",
        "items": [
          "Fish eviscerator machines - K101",
          "Fish deheading machines - K102",
          "Nobbing machines - K103",
          "Fish scaling machines - K104",
          "Fish skinning machines - K105",
          "Pinbone removers - K106",
          "Fish filleting machines - K108",
          "Fish slicing machines - K109",
          "Fish dicers - K110",
          "Fish portioning machines - K111",
          "Skewer machines - K112",
          "Brine injector machines - K113",
          "Industrial fryers - K115",
          "Smoking chambers - K116",
          "Boiling pans - K117",
          "Industrial cookers - K118",
          "Fish processing lines - K120",
          "Shellfish processing lines - K121",
          "Other fish processing equipment - K123"
        ]
      },
      {
        "subtitulo": "Fruit and Vegetable Processing",
        "items": [
          "Peeler - K201",
          "Peelers-washers-scrubbers - K202",
          "Shelling machines - K203",
          "Pitting machines - K204",
          "Pulpers - K205",
          "Coring machines - K206",
          "Stemmer-crushers - K207",
          "Leaf removers - K208",
          "Fruit and vegetable washing machines - K209",
          "Fruit and vegetable cutting machines - K211",
          "Fruits and vegetable slicing machines - K212",
          "Fruits and vegetable dicers - K213",
          "Chunking-slicing machines - K214",
          "Snipper machines - K215",
          "Juice extractors - K217",
          "Fruit juice pasteurizers - K218",
          "Olive crushers - K219",
          "Industrial fryers - K221",
          "Smoking chambers - K222",
          "Boiling pans - K223",
          "Industrial cookers - K224",
          "Fruit processing lines - K226",
          "Vegetable processing lines - K227",
          "Fruit juice production lines - K228",
          "Other fruit and vegetable production equipment - K230"
        ]
      },
      {
        "subtitulo": "Grain processing and pasta making",
        "items": [
          "Grain shelling machines - K301",
          "Flour mills - K302",
          "Rice whitening machines - K304",
          "Rice industrial cookers - K305",
          "Pasta dough mixers - K307",
          "Pasta presses - K308",
          "Pasta extruders - K309",
          "Dough sheeters - K310",
          "Pasta forming machine - K311",
          "Pasta pasteurizers - K313",
          "Pasta pre-dryers - K314",
          "Pasta dryers - K315",
          "Pasta industrial cookers - K316",
          "Pasta coolers - K317",
          "Pasta production lines - K319",
          "Couscous production lines - K320",
          "Ready-meal production lines - K321",
          "Other pasta processing equipment - K323"
        ]
      },
      {
        "subtitulo": "Dairy processing",
        "items": [
          "iry product homogenizers - K401",
          "Pasteurizers for dairy products - K402",
          "Dairy product fermenters - K403",
          "Dairy product sterilizers - K404",
          "UHT processing lines - K405",
          "Curd machines - K407",
          "Cheese draining machines - K408",
          "Cheese brining systems - K409",
          "Cheese molding machines - K410",
          "Cheese portioning machines - K412",
          "Cheese dicers - K413",
          "Cheese slicing machines - K414",
          "Cheese crust removing machines - K415",
          "Cheese grating machines - K416",
          "Cheese industrial cookers - K418",
          "Cheese smoking chambers - K419",
          "Cheese production lines - K420",
          "Cream separators - K422",
          "Butter churner machines - K423",
          "Butter cutting machine - K424",
          "Butter production lines - K425",
          "Yogurt production lines - K427",
          "Other dairy product equipment - K429"
        ]
      },
      {
        "subtitulo": "Bakery-pastry",
        "items": [
          "Dough mixer - K501",
          "Spiral dough mixers - K502",
          "Batter mixer machines - K503",
          "Molders - K504",
          "Dough sheeters - K505",
          "Dough dividers - K506",
          "Divider-rounders - K507",
          "Divider rounders - K509",
          "Rounders - K510",
          "Dough proofers - K511",
          "Sourdough fermenters - K512",
          "Depositors - K514",
          "Biscuit forming machines - K515",
          "Crepe production machines - K516",
          "Industrial bread slicers - K517",
          "Cake cutting machines - K518",
          "Refiners - K520",
          "Food coating machines - K521",
          "Chocolate tempering machines - K522",
          "Chocolate molding machine - K523",
          "Bakery ovens - K525",
          "Process freezers - K526",
          "Deep-freezers - K527",
          "Cooling tunnels - K528",
          "Climate-controlled cabinets - K529",
          "Biscuit production lines - K531",
          "Chocolate production lines - K532",
          "Bread production lines - K534",
          "Pizza production lines - K535",
          "Sandwich production lines - K536",
          "Other bakery and pastry equipment - K538"
        ]
      },
      {
        "subtitulo": "Other Food Machinery",
        "items": [
          "Graders - K601",
          "Sorters for the food industry - K602",
          "Checkweighers for the food industry - K603",
          "Centrifuges for the food industry - K604",
          "Separators for the food industry - K605",
          "Decanters for the food industry - K606",
          "Food washing machines - K607",
          "Food mills - K608",
          "Fermenters - K610",
          "Pasteurizers - K611",
          "Sterilizers for the food industry - K612",
          "Food dehydrators - K613",
          "Dryers for the food industry - K614",
          "Smoking, baking, cooking units - K615",
          "Smoke generators - K616",
          "Ovens for the food industry - K617",
          "Roasters - K619",
          "Ice makers - K620",
          "Food processing systems - K621",
          "Cheese grating machines - K623",
          "Frying lines - K625",
          "Food production lines - K626",
          "Other food industry machines - K628"
        ]
      }
    ]
  },
  {
    "titulo": "Logistics - Transport - Handling",
    "subcategorias": [
      {
        "subtitulo": "Packing and Packaging",
        "items": [
          "Bagging machines - L001",
          "Filling machine - L002",
          "Bag closing machines - L003",
          "Capping machines - L004",
          "Screw capping machines - L005",
          "Multifunction machines - L006",
          "Carton sealers - L007",
          "Impulse sealers - L008",
          "Heat sealers - L009",
          "Heat-shrink film packaging machines - L011",
          "Shrink wrapping machines - L012",
          "Vacuum packaging machines - L013",
          "Tray sealers - L014",
          "Side-sealers - L015",
          "L-sealers - L016",
          "Tray formers - L018",
          "Tray packers - L019",
          "Case packers - L020",
          "Case packer-unpackers - L021",
          "Cartoners - L022",
          "Case erectors - L023",
          "Shrink tunnels - L025",
          "Shrinkage guns - L026",
          "Stapling machines - L027",
          "Staplers - L028",
          "Palletizers - L030",
          "Depalletizers - L031",
          "Palletizers and depalletizers - L032",
          "Palletizing robot - L033",
          "Stretch wrappers - L034",
          "Hood machines - L035",
          "Strapping machines - L036",
          "Strapping tools - L037",
          "Checkweighers - L039",
          "Miscellaneous packaging machines - L040",
          "Packaging lines - L041",
          "Bottling lines - L042",
          "Palletizing and packaging lines - L043",
          "Packaging - L045",
          "Packaging film - L046",
          "Packing materials - L047",
          "Strapping seals - L048",
          "Strapping tape - L049",
          "Protective foams - L050",
          "Protection corners - L051",
          "Tubular protective netting - L052",
          "Packaging material: fill and protection, - L053",
          "Labelers - L055",
          "Label printer-applicators - L056",
          "RFID readers - L058",
          "Labels, Signage - L059",
          "RFID reader-writers - L060",
          "Packing stations - L062"
        ]
      },
      {
        "subtitulo": "Handling and Lifting",
        "items": [
          "Cranes - L101",
          "Shop cranes - L102",
          "Travel lifts - L103",
          "Gantry cranes - L104",
          "Straddle carriers - L105",
          "Overhead travelling cranes - L106",
          "Jib cranes - L107",
          "Pallet trucks - L109",
          "Hand pallet trucks - L110",
          "Stacker trucks - L111",
          "Forklifts - L112",
          "Electric forklifts - L113",
          "Reach trucks - L114",
          "Order-pickers - L115",
          "Telehandlers - L116",
          "Forklift accessories - L117",
          "Mobile weighing systems - L118",
          "Miscellaneous handling machines - L119",
          "Aerial work platforms - L121",
          "Lift tables - L122",
          "Lift gates - L123",
          "Elevators - L124",
          "Manipulators - L126",
          "Manipulator arms - L127",
          "Tube lifters - L128",
          "Vacuum lifting devices - L129",
          "Suction cups - L130",
          "Vacuum components - L131",
          "Load lifting grabs - L133",
          "Lifting beams - L134",
          "Tipping stations - L135",
          "Jacks - L136",
          "Lifting bags - L137",
          "Special handling and lifting tools - L138",
          "Hoists - L140",
          "Winches - L141",
          "Hooks - L142",
          "Straps - L143",
          "Shackles - L144",
          "Connecting links - L145",
          "Lashing chains - L146",
          "Quick links - L147",
          "Lifting pulleys - L148",
          "Swivels - L149",
          "Slings - L150",
          "Hoist rings - L151",
          "Lifting clamps, Wire Pulling Grip - L152",
          "Materials handling clamps - L153",
          "Lifting chains - L154",
          "Lifting magnets - L155",
          "Tool balancers - L156",
          "Magnetic plate lifters - L157",
          "Big bags - L158",
          "Trailers - L160",
          "AGVs - L161",
          "Industrial tractors - L162",
          "Tilt trucks - L163",
          "Self-propelled trailers - L164",
          "Semi-trailers - L165",
          "Utility vehicles - L166",
          "Moving skates - L167",
          "Carts - L168",
          "Hand trucks - L169",
          "Dollies - L170",
          "Other handling and lifting equipment - L172"
        ]
      },
      {
        "subtitulo": "Conveying",
        "items": [
          "Conveyors - L201",
          "Bucket elevators - L202",
          "Conveyor chains - L204",
          "Conveyor belts - L205",
          "Drum motors - L206",
          "Conveyor rollers - L207",
          "Ball transfer units - L208",
          "Ball transfer tables - L209",
          "Ball bars - L210",
          "Belt fasteners - L212",
          "Belt cleaners - L213",
          "Sorters - L214",
          "Accumulating tables - L215",
          "Pneumatic conveying systems - L217",
          "Rotary valves - L218",
          "Bulk and powder handling equipment - L220",
          "Industrial vibrators - L221",
          "Vibratory bowls - L222",
          "Machine feed - L223",
          "Weighing machines - L224",
          "Counting machines - L225",
          "Metal detectors - L226",
          "Magnetic separators - L227",
          "Other conveyor equipment - L229"
        ]
      },
      {
        "subtitulo": "Storage",
        "items": [
          "Cabinets - L301",
          "Lockers - L302",
          "Safes - L303",
          "Shelving - L304",
          "Shelves - L305",
          "Automated storage - L306",
          "Bacs - L307",
          "Crates - L308",
          "Picking bins - L310",
          "Intermodal containers - L311",
          "Pallet boxes - L312",
          "Pallets - L313",
          "Tanks - L314",
          "IBC containers - L315",
          "Silos - L316",
          "Jerrycans - L317",
          "Drums - L318",
          "Transport cases, suitcases - L319",
          "Assembly carts - L321",
          "Tool cabinets - L322",
          "Roll containers - L323",
          "Other storage equipment - L325"
        ]
      },
      {
        "subtitulo": "Rail Transport",
        "items": [
          "Locomotives - L401",
          "Bogies - L402",
          "Railway traction motors - L404",
          "Railway gearboxes - L405",
          "Railway wheelsets - L406",
          "Railway axles - L407",
          "Train wheels - L408",
          "Railway braking systems - L409",
          "Pantographs - L411",
          "Railway couplings - L412",
          "Train seats - L414",
          "Train driver seats - L415",
          "Train floorings - L416",
          "Train doors - L417",
          "Train air conditioning system - L418",
          "Passenger information systems - L419",
          "Railway panel PCs - L421",
          "Railway connectors - L422",
          "Railway network switches - L423",
          "Railway transformers - L424",
          "DC/DC converters for railway applications - L425",
          "Telephones for railway applications - L426",
          "Other railway products - L428"
        ]
      }
    ]
  },
  {
    "titulo": "Health - Safety - Environment",
    "subcategorias": [
      {
        "subtitulo": "Air Treatment and Noise Management",
        "items": [
          "Dust collectors - M001",
          "Inertial separator dust collectors - M002",
          "Bag dust collectors - M003",
          "Cartridge dust collectors - M004",
          "Electrostatic precipitators - M005",
          "Gas scrubbers - M006",
          "Oxidizers - M007",
          "Dehumidifiers - M008",
          "Air purifiers - M009",
          "Humidifiers - M010",
          "V-form filters - M011",
          "Pocket filters - M012",
          "Panel filters - M013",
          "Gas filters - M014",
          "Air filters - M015",
          "Air filtration units - M016",
          "Dust filtration units - M017",
          "Air filtration accessories: frames, housings, cartridges, etc. - M018",
          "Mist collectors - M020",
          "Fume extractors - M021",
          "Extractor hoods - M022",
          "Extraction arms - M023",
          "Ventilation units - M024",
          "Ventilation boxes - M025",
          "Air ducts, Flexible air duct - M026",
          "Ventilation grills - M027",
          "Air diffusers - M028",
          "Air dampers - M029",
          "Fans - M030",
          "Sound level meters - M032",
          "Vibration damping plates - M034",
          "Acoustic sandwich panels - M035",
          "Silencers - M036",
          "Sound-proof booths - M037",
          "Other soundproofing equipment - M038"
        ]
      },
      {
        "subtitulo": "Water Treatment",
        "items": [
          "Screens - M101",
          "Wastewater treatment separators - M102",
          "Water filters - M103",
          "Microfiltration units - M104",
          "Ultra-filtration units - M105",
          "Desalinators - M106",
          "Water softeners - M107",
          "Water purification units - M108",
          "Water distillation units - M109",
          "Wastewater treatment evaporators - M110",
          "Aerators - M111",
          "Wastewater treatment diffusers - M112",
          "Aerator-mixers - M113",
          "Water treatment mixers - M114",
          "Sewage lifting units - M115",
          "Wastewater pumping stations - M116",
          "Wastewater decanters - M117",
          "Disinfection units - M119",
          "Flocculators - M120",
          "Flocculation plants - M121",
          "Bioreactors, Nitrification plants - M122",
          "Sludge treatment: digestors, thickeners - M123",
          "Sewage treatment plants - M124",
          "Other water treatment equipment - M126"
        ]
      },
      {
        "subtitulo": "Waste Treatment",
        "items": [
          "Waste containers - M201",
          "Waste bins - M202",
          "Skip containers - M203",
          "Tilt trucks - M204",
          "Reverse vending machines - M205",
          "Composters - M206",
          "Bin washers - M207",
          "Big bags - M208",
          "Bin access controls - M210",
          "Waste container level sensors - M211",
          "Waste weighing systems - M212",
          "Waste collection vehicles - M214",
          "Bin lifters - M215",
          "Baling presses - M216",
          "Waste compactors - M217",
          "Shredders - M219",
          "Waste mills - M220",
          "Plastic mills - M221",
          "Waste crusher-shredders - M222",
          "Granulators - M223",
          "Crushers - M224",
          "Incinerators - M225",
          "Composting machines - M226",
          "Bottle perforators - M227",
          "Scrap grabs - M228",
          "Scrap metal shears - M229",
          "Recycling screeners - M231",
          "Recycling sorters - M232",
          "Separators - M233",
          "Eddy current separators - M234",
          "Recycling units - M235",
          "Skimmers - M236",
          "Waste treatment plants - M237",
          "Solvent distillation units - M238",
          "Briquette presses - M239",
          "Windrow turners - M240",
          "Other waste treatment equipment - M241"
        ]
      },
      {
        "subtitulo": "Personal Protective Equipment",
        "items": [
          "Safety helmets - M301",
          "Bump caps - M302",
          "Hoods - M303",
          "Protective visor - M304",
          "Welding helmets - M305",
          "Safety glasses - M306",
          "Protective goggles - M307",
          "Ear protections - M309",
          "Headsets - M310",
          "Breathing apparatuses - M311",
          "Respirators - M312",
          "Respirator filters - M313",
          "Gloves - M314",
          "Clothing - M315",
          "Safety shoes - M316",
          "Overshoes - M317",
          "Safety boots - M318",
          "Fall arrest lanyards - M320",
          "Fall arrest anchors - M321",
          "Rope clamps - M322",
          "Fall-arrest ropes - M323",
          "Lifelines - M324",
          "Fall arrest lanyards - M325",
          "Harnesses - M326",
          "Fall arrest belts - M327",
          "Fall arrest safety nets - M328",
          "Fall-arrest barriers - M329",
          "Carabiners - M330",
          "Quick links - M331",
          "Other fall prevention equipment - M332",
          "Safety showers - M334",
          "Decontamination systems - M335",
          "Other personal protective equipment - M337"
        ]
      },
      {
        "subtitulo": "Building Security and Machine Safety",
        "items": [
          "Alarm annunciators - M401",
          "Obstruction lights - M402",
          "Stack lights - M403",
          "Beacons - M404",
          "Buzzers - M405",
          "Alarm buzzers - M406",
          "Sounders - M407",
          "Warning devices - M408",
          "Warning horns - M409",
          "Voice sounders - M410",
          "Gates - M411",
          "Other access control equipment - M412",
          "Photoelectric cells - M414",
          "Intrusion detectors - M415",
          "Headsets - M416",
          "Loudspeakers - M417",
          "Intercoms - M418",
          "Microphones - M419",
          "Telephones - M420",
          "Other voice communications equipment - M421",
          "Emergency lighting - M422",
          "Camera control units - M423",
          "Video surveillance monitors - M424",
          "Video servers - M425",
          "Video recorders - M426",
          "Other video surveillance equipment - M427",
          "Other safety equipment - M429",
          "Structural protection: Bearings, Posts, Protective systems - M430",
          "Structural protection: Padlocks, Security ties, Seals - M431",
          "Containment bunds - M433",
          "Spill platforms - M434",
          "Spill pallets - M435",
          "Light curtains - M437",
          "Machine guards - M438",
          "Partitions - M439",
          "Telescopic covers - M440",
          "Roll-up covers - M441",
          "Other machine protection - M442",
          "Machine protection: Machine safety devices - M443",
          "PAT testers - M445",
          "Fire detection systems - M446",
          "Fire detectors - M447",
          "Smoke detectors - M448",
          "Fire prevention equipment - M449",
          "Firefighting equipment - M450",
          "AED - M452",
          "Environmental protection - M454",
          "(HSE) Electrical Safety / Lineman tools / Hot sticks - M455"
        ]
      },
      {
        "subtitulo": "Cleaning and Hygiene",
        "items": [
          "Vacuum cleaners - M501",
          "Sweepers - M502",
          "Scrubber-dryers - M504",
          "Single-disc floor machines - M505",
          "Floor burnishers - M506",
          "Steam cleaners - M507",
          "High-pressure cleaners - M508",
          "Dry ice blasters - M509",
          "Cleaning trolleys - M511",
          "Ozone generators - M513",
          "Disinfectant sprayers - M514",
          "Other cleaning equipment - M516"
        ]
      }
    ]
  },
  {
    "titulo": "Building - Construction",
    "subcategorias": [
      {
        "subtitulo": "Industrial Building Equipment",
        "items": [
          "Buildings - N001",
          "Partitions, Modular construction elements - N003",
          "Industrial mezzanines - N004",
          "Staircases - N005",
          "Ladders - N006",
          "Mats - N007",
          "Gratings - N008",
          "Floor coverings - N009",
          "Dock levelers - N011",
          "Loading ramps - N012",
          "Dock shelters - N013",
          "Other loading dock equipment - N014",
          "Industrial doors - N015",
          "Industrial door automation and accessories - N016",
          "Air curtains - N017",
          "Fences - N019",
          "Gates - N020",
          "Barriers - N021",
          "Retractable bollards - N022",
          "Fixed bollards - N023",
          "Turnstiles - N024",
          "Access control terminal - N025",
          "Fingerprint readers - N026",
          "Other access control equipment - N027",
          "Air heater units - N029",
          "Hot air generators - N030",
          "Radiant heaters - N031",
          "Heat pumps - N032",
          "Other heating equipment - N033",
          "Air conditioners - N034",
          "Air handling units - N035",
          "Other air conditioning equipment - N036",
          "Ventilation units - N037",
          "Ventilation grills - N038",
          "Air ducts - N039",
          "Emergency lighting - N041",
          "Lighting - N042",
          "LED bulbs - N044",
          "Urban lamp-posts - N045",
          "Other lighting equipment - N046",
          "Workstations, Workbenches - N048"
        ]
      },
      {
        "subtitulo": "Construction and Mining Equipment",
        "items": [
          "Excavators - N101",
          "Backhoe loaders - N102",
          "Loaders - N103",
          "Skid steer loaders - N104",
          "Dumpers - N105",
          "Bulldozers - N106",
          "Motor graders - N107",
          "Road rollers - N108",
          "Vibratory plates - N109",
          "Pavers - N110",
          "Cold planers - N111",
          "Road work equipment - N112",
          "Drilling rigs - N114",
          "Core bits - N115",
          "Drilling equipment - N116",
          "Pile drivers - N117",
          "Piling equipment - N118",
          "Trenchers - N119",
          "Jumbos drilling rigs - N120",
          "Roadheaders - N121",
          "Tunnel boring machines and equipment - N122",
          "Demolition shears - N123",
          "Hydraulic crushers - N124",
          "Demolition equipment - N125",
          "Mixer trucks - N127",
          "Other concrete equipment - N128",
          "Formwork - N129",
          "Formwork equipment - N130",
          "Scaffolding - N131",
          "Scaffolding equipment - N132",
          "Dump trucks - N134",
          "Crushers - N135",
          "Other open-pit mining and quarrying equipment - N136",
          "Underground trucks - N137",
          "Forestry harvesters - N139",
          "Skidders - N140",
          "Forestry forwarders - N141",
          "Log loaders - N142",
          "Other forestry equipment - N143",
          "Other construction equipment - N145",
          "Trailers - N146",
          "Utility vehicles - N147",
          "Tires - N149",
          "Tracks - N150",
          "Construction equipment buckets, Shears, Grabs - N151",
          "Other construction equipment material - N152"
        ]
      },
      {
        "subtitulo": "Production of building materials",
        "items": [
          "Concrete batching plants - N201",
          "Concrete skips - N202",
          "Concrete pumps - N203",
          "Self-loading concrete mixers - N204",
          "Concrete product production lines - N205",
          "Concrete testing machines - N206",
          "Concrete mixers - N207",
          "Cement silos - N208",
          "Block making machine - N210",
          "Concrete block presses - N211",
          "Asphalt plants - N213",
          "Screen plates - N214",
          "Stationary screeners - N215",
          "Stone cutting machines - N217",
          "Stone polishing machines - N218",
          "Stone and concrete saws - N219",
          "Splitting machines - N220",
          "Concrete reinforcement bending machines - N222",
          "Bar straightening machines - N223",
          "Metal cutting machines - N224",
          "Other machines for building material production - N226"
        ]
      },
      {
        "subtitulo": "Construction tools",
        "items": [
          "Rammers - N301",
          "Pole tampers - N302",
          "Vibratory plates - N303",
          "Screeding systems - N304",
          "Concrete mixers - N306",
          "Wet screeds - N307",
          "Internal vibrators - N308",
          "Power trowels - N309",
          "Floor saws - N310",
          "Stone and concrete saws - N311",
          "Wood saws - N312",
          "Groove-cutting machines - N313",
          "Concrete floor sanders - N315",
          "Portable grinders - N316",
          "Scabblers - N317",
          "Construction site rotary hammers - N318",
          "Slab laying machines - N320",
          "Laying clamps - N321",
          "Block lifters - N322",
          "Paving block extractors - N323",
          "Block cutters - N324",
          "Manhole cover lifters - N325",
          "Paint line removal machines - N326",
          "Paint stripping machines - N327",
          "Levels - N329",
          "Theodolites - N330",
          "Total stations - N331",
          "Site lasers - N332",
          "Construction site receivers - N333",
          "Laser receivers - N334",
          "Distance meters - N335",
          "Conductivity meters - N336",
          "Field controllers - N337",
          "Mapping systems - N338",
          "Surveying systems - N339",
          "Surveying receivers - N340",
          "GNSS receivers - N341",
          "Step ladders - N343",
          "Other construction tools - N344"
        ]
      }
    ]
  },
  {
    "titulo": "SMALL FARM EQUIPMENT",
    "subcategorias": [
      {
        "subtitulo": "SMALL FARM TOOLS",
        "items": [
          "Rototillers - O001",
          "Motor hoes - O002",
          "Dethatchers - O003",
          "Turf cutters - O005",
          "Chainsaws - O007",
          "Wood chippers - O008",
          "Stump grinders - O009",
          "Wood splitters - O010",
          "Electric pruning shears - O012",
          "Manual pruning shears - O013",
          "Loppers - O014",
          "Grafting knives - O015",
          "Vine binders - O016",
          "Hedge trimmers - O017",
          "Brush cutter - O018",
          "Edgers - O019",
          "Hoes, mattock - O020",
          "Hand saws - O021",
          "Pole saws - O022",
          "Leaf blowers - O023",
          "Leaf vacuums - O024",
          "Other pruning tools - O025",
          "Pickaxe, Pickax - O026",
          "Shovels - O027",
          "Spades - O028",
          "Garden forks - O029",
          "Hay pitchforks - O030",
          "Hand rakes - O031",
          "Olive rakes - O032",
          "Axes - O033",
          "Bale loaders - O034",
          "Wheelbarrows - O036",
          "Brooms - O037",
          "Manual seeders - O038",
          "Jab planters - O039",
          "Backpack sprayers - O040",
          "Spraying guns - O041",
          "Watering cans - O042",
          "Foggers - O043",
          "Buckets - O044",
          "Picking buckets - O045",
          "Picking bags - O046",
          "Fruit pickers - O047",
          "Sieves - O048",
          "Other small farm tools - O049"
        ]
      },
      {
        "subtitulo": "GROUNDS CARE EQUIPMENT",
        "items": [
          "Riding lawn mowers - O101",
          "Push lawn-mowers - O102",
          "Robotic lawn mowers - O103",
          "Motor-mowers - O104",
          "Reach mowers - O105",
          "Rotary cutters - O106",
          "Snowplow blades - O108",
          "Snow blowers - O109",
          "Salt spreaders - O110",
          "Groundcare sweepers - O111",
          "Barn sweepers - O112",
          "High pressure washers - O113",
          "Mini dumpers - O115",
          "Backhoes - O116",
          "Excavators - O117",
          "Post drivers - O118",
          "Earth augers - O119",
          "Wire unwinding machines - O120",
          "Hydroseeders - O121",
          "Dredgers - O122",
          "Mowing boats - O123",
          "Other grounds care equipment - O125"
        ]
      }
    ]
  },
  {
    "titulo": "SERVICES",
    "subcategorias": [
      {
        "subtitulo": "CERTIFICATIONS",
        "items": [
          "Dielectric Test Certificate - Z001",
          "ONAC-Accredited Laboratory Calibration Certificate - Z002",
          "NON-Accredited Laboratory Calibration Certificate - Z003",
          "Functional Equipment Test Certificate - Z004",
          "Generator Integrity Certificate - Z005",
          "Synchronization Test Certificate - Z006",
          "Electrical Adaptation Compliance Certificate - Z007",
          "Technical Equipment Inspection Certificate - Z008",
          "Protection System Testing Certificate - Z009",
          "Electrical Continuity Certificate - Z010"
        ]
      },
      {
        "subtitulo": "LABOR / TECHNICAL WORK",
        "items": [
          "Installation and Training - Z101",
          "Technical Service: Preventive Maintenance, Diagnosis, Inspection, Adaptation & Repair - Z102",
          "Service Plan – Care Plan - Z103",
          "Medium-Voltage Power Line Inspection using Drone - Z104",
          "Accounting & Tax Consulting Fees - Z105",
          "Technical Adjustments and On-Site Configuration - Z106",
          "Engineering or Programming Technical Hours - Z107",
          "Remote Technical Assistance - Z108",
          "Reserved for future expansion - Z109"
        ]
      },
      {
        "subtitulo": "LOGISTICS",
        "items": [
          "Customs Expenses - Z201",
          "Taxes - Z202",
          "Internal Dispatch - Z203",
          "Warehouse Handling - Z204",
          "Loading / Unloading - Z205",
          "Special Packaging - Z206",
          "National Transportation - Z207",
          "Sensitive Equipment Handling - Z208",
          "Reserved for future expansion - Z209",
          "Data acquisition, Data Management - Z210"
        ]
      }
    ]
  }
];