const marcasPaises = {
  "3M": "United States",
  "AERVOE": "United States",
  "AIRTOOLS": "United States",
  "ALLEN BRADLEY": "United States",
  "AMERIC": "United States",
  "AMPROBE": "United States",
  "APOLLO": "United States",
  "APPLETON": "United States",
  "ARC GUARD": "United States",
  "AURAND": "United States",
  "AVTRON": "United States",
  "BAKER HUGHES": "United States",
  "BARTEC": "Germany",
  "BENTLY": "United States",
  "BIRKOSIT": "Germany",
  "BOMBADUR": "United States",
  "BURNDY": "United States",
  "CAT": "United States",
  "COMET": "Italy",
  "CONTROLAIR": "United States",
  "COPPUS": "United States",
  "CORDEX": "Canada",
  "COREMO": "Italy",
  "CRE": "France",
  "CROSBY": "United States",
  "CUMMINS": "United States",
  "DEEP SEA": "United Kingdom",
  "DEFELSKO": "United States",
  "DETCON": "United States",
  "DEUTZ": "Germany",
  "DHV": "Netherlands",
  "DJI": "China",
  "DOOSAN": "South Korea",
  "DRESSER TEXSTEAM": "United States",
  "DRILLFIX": "Germany",
  "DURAPULSE": "United States",
  "DWT": "Switzerland",
  "DYNAGEN": "Canada",
  "EASY LASER": "Sweden",
  "EBMPAPST": "Germany",
  "EDILGRAPPA": "Italy",
  "ELCOMETER": "United Kingdom",
  "ELITE": "China",
  "EMERSON": "United States",
  "ENERPAC": "United States",
  "ESAB": "Sweden",
  "EXTECH": "United States",
  "FALCON": "United States",
  "FAMECA": "France",
  "FISHER": "United States",
  "FIXTURLASER": "Sweden",
  "FLIR": "United States",
  "FLUKE": "United States",
  "FW MURPHY": "United States",
  "GATES": "United States",
  "GATOR": "United States",
  "GE PANAMETRICS": "United States",
  "GENERAC": "United States",
  "GENIUS": "Taiwan",
  "GETAC": "Taiwan",
  "GFUVE": "China",
  "GORE": "United States",
  "GRACO": "United States",
  "GREENLEE": "United States",
  "GRIFFCO": "United States",
  "HASTINGS": "United States",
  "HILTI": "Liechtenstein",
  "HIOKI": "Japan",
  "HTH": "United States",
  "HUSKIE": "United States",
  "HYDRAJAWS": "United Kingdom",
  "HYTERA": "China",
  "INGPRO": "Unknown/International",
  "INSPIRED ENERGY": "United States",
  "ISAFE": "Germany",
  "ITL": "United Kingdom",
  "JOHN DEERE": "United States",
  "JUROP": "Italy",
  "KAISHAN": "China",
  "KAMAT": "Germany",
  "KANE": "United Kingdom",
  "KEWTECH": "United Kingdom",
  "KEY FIRE HOSE": "United States",
  "KILOVOLT": "United States",
  "KLUBER": "Germany",
  "KRUG": "Germany",
  "KTC": "Japan",
  "KUBOTA": "Japan",
  "KUDOS": "Taiwan",
  "KYORITSU": "Japan",
  "LAKELAND": "United States",
  "LAPMASTER": "United States",
  "LEICA": "Switzerland",
  "LEISTER": "Switzerland",
  "LEMASA": "Brazil",
  "LEROY SOMER": "France",
  "LINCOLN": "United States",
  "LISTER PETTER": "United Kingdom",
  "LOCTITE": "United States",
  "MAC": "United States",
  "MAGSWITCH": "United States",
  "MARSHALL EXCELSIOR": "United States",
  "MARTEL": "United States",
  "MAUCOTOOLS": "Italy",
  "METABO": "Germany",
  "METREL": "Slovenia",
  "MILLER": "United States",
  "MILTON ROY": "United States",
  "MILWAUKEE": "United States",
  "MOBIR": "China",
  "MOMENTIVE": "United States",
  "MOSEBACH": "United States",
  "MSA": "United States",
  "NATIONAL": "United States",
  "NOV": "United States",
  "OFMER": "Italy",
  "OIL WATCH": "United States",
  "OMICRON": "Austria",
  "PANDUIT": "United States",
  "PARKER": "United States",
  "PDMA": "United States",
  "PENTAIR": "United States",
  "PERKINS": "United Kingdom",
  "PHILLIPS": "Netherlands",
  "PIETRO FIORENTINI": "Italy",
  "PIGS UNLIMITED": "United States",
  "PLASTIGAUGE": "United Kingdom",
  "PRECISION BRAND": "United States",
  "PRESYS": "Brazil",
  "PRETUL": "Mexico",
  "PROMINENT": "Germany",
  "PROTEM": "France",
  "PUMPWORKS": "United States",
  "QLIGHT": "South Korea",
  "RAYCHEM": "United States",
  "REAL JACKS": "United States",
  "REZONTECH": "South Korea",
  "RICE LAKE": "United States",
  "SCHULZ": "Brazil",
  "SCOTT": "United States",
  "SDT": "Belgium",
  "SEW": "Germany",
  "SHIBUYA": "Japan",
  "SIEMENS": "Germany",
  "SIXNET": "United States",
  "SKF": "Sweden",
  "SOFAMEL": "Spain",
  "SOLUCAO": "Brazil",
  "SPLITSTAR": "Japan",
  "STAHT": "Germany",
  "STAMFORD": "United Kingdom",
  "STARRETT": "United States",
  "STREAMLIGHT": "United States",
  "SWAGELOK": "United States",
  "SYLVANIA": "United States",
  "TEHMA": "Italy",
  "TELEDYNE": "United States",
  "TENTECH": "Brazil",
  "TIME ELECTRONICS": "United Kingdom",
  "TOKU": "Japan",
  "TRIMBLE": "United States",
  "TUFF BUCKET": "United States",
  "TWECO": "United States",
  "ULB": "United States",
  "ULIRVISION": "China",
  "ULTRAPROBE": "United States",
  "UNIFLEX": "Germany",
  "UNIOR": "Slovenia",
  "UNIT T": "China",
  "VDO": "Germany",
  "VEGA": "Germany",
  "VICTOR": "United States",
  "WIKA": "Germany",
  "WOODWARD": "United States",
  "YOKOGAWA": "Japan",
  "YTO": "China",
  "ZIEHL-ABEGG": "Germany"
};
