const marcasPaises = {
    "3M": "Estados Unidos",
    "AERVOE": "Estados Unidos",
    "AIRTOOLS": "Estados Unidos",
    "ALLEN BRADLEY": "Estados Unidos",
    "AMERIC": "Estados Unidos",
    "AMPROBE": "Estados Unidos",
    "APOLLO": "Estados Unidos",
    "APPLETON": "Estados Unidos",
    "ARC GUARD": "Estados Unidos",
    "AURAND": "Estados Unidos",
    "AVTRON": "Estados Unidos",
    "BAKER HUGHES": "Estados Unidos",
    "BARTEC": "Alemania",
    "BENTLY": "Estados Unidos",
    "BIRKOSIT": "Alemania",
    "BOMBADUR": "Estados Unidos",
    "BURNDY": "Estados Unidos",
    "CAT": "Estados Unidos",
    "COMET": "Italia",
    "CONTROLAIR": "Estados Unidos",
    "COPPUS": "Estados Unidos",
    "CORDEX": "Canadá",
    "COREMO": "Italia",
    "CRE": "Francia",
    "CROSBY": "Estados Unidos",
    "CUMMINS": "Estados Unidos",
    "DEEP SEA": "Reino Unido",
    "DEFELSKO": "Estados Unidos",
    "DETCON": "Estados Unidos",
    "DEUTZ": "Alemania",
    "DHV": "Países Bajos",
    "DJI": "China",
    "DOOSAN": "Corea del Sur",
    "DRESSER TEXSTEAM": "Estados Unidos",
    "DRILLFIX": "Alemania",
    "DURAPULSE": "Estados Unidos",
    "DWT": "Suiza",
    "DYNAGEN": "Canadá",
    "EASY LASER": "Suecia",
    "EBMPAPST": "Alemania",
    "EDILGRAPPA": "Italia",
    "ELCOMETER": "Reino Unido",
    "ELITE": "China",
    "EMERSON": "Estados Unidos",
    "ENERPAC": "Estados Unidos",
    "ESAB": "Suecia",
    "EXTECH": "Estados Unidos",
    "FALCON": "Estados Unidos",
    "FAMECA": "Francia",
    "FISHER": "Estados Unidos",
    "FIXTURLASER": "Suecia",
    "FLIR": "Estados Unidos",
    "FLUKE": "Estados Unidos",
    "FW MURPHY": "Estados Unidos",
    "GATES": "Estados Unidos",
    "GATOR": "Estados Unidos",
    "GE PANAMETRICS": "Estados Unidos",
    "GENERAC": "Estados Unidos",
    "GENIUS": "Taiwán",
    "GETAC": "Taiwán",
    "GFUVE": "China",
    "GORE": "Estados Unidos",
    "GRACO": "Estados Unidos",
    "GREENLEE": "Estados Unidos",
    "GRIFFCO": "Estados Unidos",
    "HASTINGS": "Estados Unidos",
    "HILTI": "Liechtenstein",
    "HIOKI": "Japón",
    "HTH": "Estados Unidos",
    "HUSKIE": "Estados Unidos",
    "HYDRAJAWS": "Reino Unido",
    "HYTERA": "China",
    "INGPRO": "Desconocido/Internacional",
    "INSPIRED ENERGY": "Estados Unidos",
    "ISAFE": "Alemania",
    "ITL": "Reino Unido",
    "JOHN DEERE": "Estados Unidos",
    "JUROP": "Italia",
    "KAISHAN": "China",
    "KAMAT": "Alemania",
    "KANE": "Reino Unido",
    "KEWTECH": "Reino Unido",
    "KEY FIRE HOSE": "Estados Unidos",
    "KILOVOLT": "Estados Unidos",
    "KLUBER": "Alemania",
    "KRUG": "Alemania",
    "KTC": "Japón",
    "KUBOTA": "Japón",
    "KUDOS": "Taiwán",
    "KYORITSU": "Japón",
    "LAKELAND": "Estados Unidos",
    "LAPMASTER": "Estados Unidos",
    "LEICA": "Suiza",
    "LEISTER": "Suiza",
    "LEMASA": "Brasil",
    "LEROY SOMER": "Francia",
    "LINCOLN": "Estados Unidos",
    "LISTER PETTER": "Reino Unido",
    "LOCTITE": "Estados Unidos",
    "MAC": "Estados Unidos",
    "MAGSWITCH": "Estados Unidos",
    "MARSHALL EXCELSIOR": "Estados Unidos",
    "MARTEL": "Estados Unidos",
    "MAUCOTOOLS": "Italia",
    "METABO": "Alemania",
    "METREL": "Eslovenia",
    "MILLER": "Estados Unidos",
    "MILTON ROY": "Estados Unidos",
    "MILWAUKEE": "Estados Unidos",
    "MOBIR": "China",
    "MOMENTIVE": "Estados Unidos",
    "MOSEBACH": "Estados Unidos",
    "MSA": "Estados Unidos",
    "NATIONAL": "Estados Unidos",
    "NOV": "Estados Unidos",
    "OFMER": "Italia",
    "OIL WATCH": "Estados Unidos",
    "OMICRON": "Austria",
    "PANDUIT": "Estados Unidos",
    "PARKER": "Estados Unidos",
    "PDMA": "Estados Unidos",
    "PENTAIR": "Estados Unidos",
    "PERKINS": "Reino Unido",
    "PHILLIPS": "Países Bajos",
    "PIETRO FIORENTINI": "Italia",
    "PIGS UNLIMITED": "Estados Unidos",
    "PLASTIGAUGE": "Reino Unido",
    "PRECISION BRAND": "Estados Unidos",
    "PRESYS": "Brasil",
    "PRETUL": "México",
    "PROMINENT": "Alemania",
    "PROTEM": "Francia",
    "PUMPWORKS": "Estados Unidos",
    "QLIGHT": "Corea del Sur",
    "RAYCHEM": "Estados Unidos",
    "REAL JACKS": "Estados Unidos",
    "REZONTECH": "Corea del Sur",
    "RICE LAKE": "Estados Unidos",
    "SCHULZ": "Brasil",
    "SCOTT": "Estados Unidos",
    "SDT": "Bélgica",
    "SEW": "Alemania",
    "SHIBUYA": "Japón",
    "SIEMENS": "Alemania",
    "SIXNET": "Estados Unidos",
    "SKF": "Suecia",
    "SOFAMEL": "España",
    "SOLUCAO": "Brasil",
    "SPLITSTAR": "Japón",
    "STAHT": "Alemania",
    "STAMFORD": "Reino Unido",
    "STARRETT": "Estados Unidos",
    "STREAMLIGHT": "Estados Unidos",
    "SWAGELOK": "Estados Unidos",
    "SYLVANIA": "Estados Unidos",
    "TEHMA": "Italia",
    "TELEDYNE": "Estados Unidos",
    "TENTECH": "Brasil",
    "TIME ELECTRONICS": "Reino Unido",
    "TOKU": "Japón",
    "TRIMBLE": "Estados Unidos",
    "TUFF BUCKET": "Estados Unidos",
    "TWECO": "Estados Unidos",
    "ULB": "Estados Unidos",
    "ULIRVISION": "China",
    "ULTRAPROBE": "Estados Unidos",
    "UNIFLEX": "Alemania",
    "UNIOR": "Eslovenia",
    "UNIT T": "China",
    "VDO": "Alemania",
    "VEGA": "Alemania",
    "VICTOR": "Estados Unidos",
    "WIKA": "Alemania",
    "WOODWARD": "Estados Unidos",
    "YOKOGAWA": "Japón",
    "YTO": "China",
    "ZIEHL-ABEGG": "Alemania"
  };